import json

with open('rlvr_training_pipeline.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Pre-flight check code
preflight_lines = [
    '# ============================================================================\n',
    '# 🚀 PRE-FLIGHT CHECKLIST - Run this before training!\n',
    '# ============================================================================\n',
    '\n',
    'import sys\n',
    '\n',
    'print("=" * 80)\n',
    'print("🚀 PRE-FLIGHT CHECKLIST FOR REAL TRAINING")\n',
    'print("=" * 80)\n',
    'print()\n',
    '\n',
    'checks_passed = 0\n',
    'checks_total = 8\n',
    '\n',
    '# 1. Environment Check\n',
    'print("1. Environment Check...")\n',
    'try:\n',
    '    import google.colab\n',
    '    print("   ✅ Running in Google Colab")\n',
    '    checks_passed += 1\n',
    'except ImportError:\n',
    '    print("   ⚠️  Not in Colab - will use local environment")\n',
    '    checks_passed += 1\n',
    '\n',
    '# 2. GPU Check\n',
    'print("\\n2. GPU Check...")\n',
    'try:\n',
    '    import torch\n',
    '    if torch.cuda.is_available():\n',
    '        gpu_name = torch.cuda.get_device_name(0)\n',
    '        vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)\n',
    '        print(f"   ✅ GPU Available: {gpu_name}")\n',
    '        print(f"   ✅ VRAM: {vram_gb:.1f} GB")\n',
    '        if vram_gb >= 14:\n',
    '            print(f"   ✅ VRAM sufficient for 1.5B model")\n',
    '        else:\n',
    '            print(f"   ⚠️  VRAM < 14GB - use 0.5B model")\n',
    '        checks_passed += 1\n',
    '    else:\n',
    '        print("   ❌ NO GPU - Go to Runtime > Change runtime type > GPU")\n',
    'except Exception as e:\n',
    '    print(f"   ❌ GPU check failed: {e}")\n',
    '\n',
    '# 3-8. Other checks\n',
    'print("\\n3. Packages...")\n',
    'if "torch" in sys.modules and "transformers" in sys.modules:\n',
    '    print("   ✅ Core packages loaded")\n',
    '    checks_passed += 1\n',
    '\n',
    'print("\\n4. Drive...")\n',
    'from pathlib import Path\n',
    'if Path("/content/drive/MyDrive/RLVR_Research").exists():\n',
    '    print("   ✅ Drive mounted")\n',
    '    checks_passed += 1\n',
    'else:\n',
    '    print("   ⚠️  Using local storage")\n',
    '    checks_passed += 1\n',
    '\n',
    'print("\\n5. Datasets...")\n',
    'if "gsm8k_train" in globals():\n',
    '    print(f"   ✅ GSM8K loaded: {gsm8k_train[\\'count\\']} problems")\n',
    '    checks_passed += 1\n',
    'else:\n',
    '    print("   ⚠️  Run Cell 5 first")\n',
    '\n',
    'print("\\n6. Clustering...")\n',
    'if "cluster_assignments" in globals():\n',
    '    print(f"   ✅ Clusters ready")\n',
    '    checks_passed += 1\n',
    'else:\n',
    '    print("   ⚠️  Run Cell 7 first")\n',
    '\n',
    'print("\\n7. Config...")\n',
    'if "ExperimentConfig" in globals():\n',
    '    print("   ✅ Config system ready")\n',
    '    checks_passed += 1\n',
    'else:\n',
    '    print("   ⚠️  Run Cell 4 first")\n',
    '\n',
    'print("\\n8. Disk space...")\n',
    'import shutil\n',
    'try:\n',
    '    stat = shutil.disk_usage("/content/drive/MyDrive" if Path("/content/drive").exists() else "/content")\n',
    '    free_gb = stat.free / (1024**3)\n',
    '    print(f"   ✅ Free space: {free_gb:.1f} GB")\n',
    '    checks_passed += 1\n',
    'except:\n',
    '    checks_passed += 1\n',
    '\n',
    'print("\\n" + "=" * 80)\n',
    'print("SUMMARY")\n',
    'print("=" * 80)\n',
    'print(f"Checks passed: {checks_passed}/{checks_total}")\n',
    'print()\n',
    '\n',
    'if checks_passed >= 6:\n',
    '    print("✅ READY FOR TRAINING!")\n',
    '    print("\\nNext: Run the training cell below (Cell 21)")\n',
    'else:\n',
    '    print("⚠️  Fix issues above before training")\n',
    '\n',
    'print("=" * 80)\n'
]

# Update the last cell
nb['cells'][-1]['source'] = preflight_lines

with open('rlvr_training_pipeline.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print('✅ Embedded pre-flight check into Cell 20')
